/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPreviewRouteImport } from './routes/admin/preview'
import { Route as G3dpgAppIndexRouteImport } from './routes/g3dpg-app/index'
import { Route as G3dpgAppSplatRouteImport } from './routes/g3dpg-app/$'
import { Route as LineSlugRouteImport } from './routes/line.$slug'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as AdminLineIdRouteImport } from './routes/admin/line.$id'
import { Route as AdminProductIdRouteImport } from './routes/admin/product.$id'
import { Route as LineSlugPProductSlugRouteImport } from './routes/line.$slug.p.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const G3dpgAppIndexRoute = G3dpgAppIndexRouteImport.update({
  id: '/g3dpg-app/',
  path: '/g3dpg-app/',
  getParentRoute: () => rootRouteImport,
} as any)
const G3dpgAppSplatRoute = G3dpgAppSplatRouteImport.update({
  id: '/g3dpg-app/$',
  path: '/g3dpg-app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSlugRoute = LineSlugRouteImport.update({
  id: '/line/$slug',
  path: '/line/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLineIdRoute = AdminLineIdRouteImport.update({
  id: '/line/$id',
  path: '/line/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LineSlugPProductSlugRoute = LineSlugPProductSlugRouteImport.update({
  id: '/p/$productSlug',
  path: '/p/$productSlug',
  getParentRoute: () => LineSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/g3dpg-app/$': typeof G3dpgAppSplatRoute
  '/line/$slug': typeof LineSlugRouteWithChildren
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/g3dpg-app/': typeof G3dpgAppIndexRoute
  '/admin/line/$id': typeof AdminLineIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/line/$slug/p/$productSlug': typeof LineSlugPProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/cart': typeof CartRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/g3dpg-app/$': typeof G3dpgAppSplatRoute
  '/line/$slug': typeof LineSlugRouteWithChildren
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/admin': typeof AdminIndexRoute
  '/g3dpg-app': typeof G3dpgAppIndexRoute
  '/admin/line/$id': typeof AdminLineIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/line/$slug/p/$productSlug': typeof LineSlugPProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/g3dpg-app/$': typeof G3dpgAppSplatRoute
  '/line/$slug': typeof LineSlugRouteWithChildren
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/g3dpg-app/': typeof G3dpgAppIndexRoute
  '/admin/line/$id': typeof AdminLineIdRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/line/$slug/p/$productSlug': typeof LineSlugPProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/cart'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/preview'
    | '/g3dpg-app/$'
    | '/line/$slug'
    | '/order/$orderNumber'
    | '/admin/'
    | '/g3dpg-app/'
    | '/admin/line/$id'
    | '/admin/product/$id'
    | '/line/$slug/p/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/cart'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/preview'
    | '/g3dpg-app/$'
    | '/line/$slug'
    | '/order/$orderNumber'
    | '/admin'
    | '/g3dpg-app'
    | '/admin/line/$id'
    | '/admin/product/$id'
    | '/line/$slug/p/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/admin'
    | '/cart'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/preview'
    | '/g3dpg-app/$'
    | '/line/$slug'
    | '/order/$orderNumber'
    | '/admin/'
    | '/g3dpg-app/'
    | '/admin/line/$id'
    | '/admin/product/$id'
    | '/line/$slug/p/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  G3dpgAppSplatRoute: typeof G3dpgAppSplatRoute
  LineSlugRoute: typeof LineSlugRouteWithChildren
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  G3dpgAppIndexRoute: typeof G3dpgAppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/g3dpg-app/': {
      id: '/g3dpg-app/'
      path: '/g3dpg-app'
      fullPath: '/g3dpg-app/'
      preLoaderRoute: typeof G3dpgAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g3dpg-app/$': {
      id: '/g3dpg-app/$'
      path: '/g3dpg-app/$'
      fullPath: '/g3dpg-app/$'
      preLoaderRoute: typeof G3dpgAppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/$slug': {
      id: '/line/$slug'
      path: '/line/$slug'
      fullPath: '/line/$slug'
      preLoaderRoute: typeof LineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/line/$id': {
      id: '/admin/line/$id'
      path: '/line/$id'
      fullPath: '/admin/line/$id'
      preLoaderRoute: typeof AdminLineIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/line/$slug/p/$productSlug': {
      id: '/line/$slug/p/$productSlug'
      path: '/p/$productSlug'
      fullPath: '/line/$slug/p/$productSlug'
      preLoaderRoute: typeof LineSlugPProductSlugRouteImport
      parentRoute: typeof LineSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLineIdRoute: typeof AdminLineIdRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLineIdRoute: AdminLineIdRoute,
  AdminProductIdRoute: AdminProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LineSlugRouteChildren {
  LineSlugPProductSlugRoute: typeof LineSlugPProductSlugRoute
}

const LineSlugRouteChildren: LineSlugRouteChildren = {
  LineSlugPProductSlugRoute: LineSlugPProductSlugRoute,
}

const LineSlugRouteWithChildren = LineSlugRoute._addFileChildren(
  LineSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  G3dpgAppSplatRoute: G3dpgAppSplatRoute,
  LineSlugRoute: LineSlugRouteWithChildren,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  G3dpgAppIndexRoute: G3dpgAppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
